/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as AuthProductsRouteRouteImport } from './routes/_auth/products/route'
import { Route as AuthPicturesRouteRouteImport } from './routes/_auth/pictures/route'
import { Route as AuthMembersRouteRouteImport } from './routes/_auth/members/route'
import { Route as AuthMachinesRouteRouteImport } from './routes/_auth/machines/route'
import { Route as AuthProductsIndexRouteImport } from './routes/_auth/products/index'
import { Route as AuthPicturesIndexRouteImport } from './routes/_auth/pictures/index'
import { Route as AuthMembersIndexRouteImport } from './routes/_auth/members/index'
import { Route as AuthMachinesIndexRouteImport } from './routes/_auth/machines/index'
import { Route as InviteAcceptTokenRouteImport } from './routes/invite/accept/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEdgeV1UsersRouteImport } from './routes/api/edge/v1/users'
import { Route as ApiEdgeV1PairRouteImport } from './routes/api/edge/v1/pair'
import { Route as ApiEdgeV1HeartbeatRouteImport } from './routes/api/edge/v1/heartbeat'
import { Route as AuthMachinesMachineIdSmartfridgeRouteRouteImport } from './routes/_auth/machines/$machineId/smartfridge/route'
import { Route as AuthMachinesMachineIdCompartmentsRouteRouteImport } from './routes/_auth/machines/$machineId/compartments/route'
import { Route as AuthMachinesMachineIdSmartfridgeIndexRouteImport } from './routes/_auth/machines/$machineId/smartfridge/index'
import { Route as AuthMachinesMachineIdCompartmentsIndexRouteImport } from './routes/_auth/machines/$machineId/compartments/index'
import { Route as ApiEdgeV1SyncPushRouteImport } from './routes/api/edge/v1/sync/push'
import { Route as ApiEdgeV1SyncPullRouteImport } from './routes/api/edge/v1/sync/pull'
import { Route as ApiEdgeV1AuthLoginRouteImport } from './routes/api/edge/v1/auth/login'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProductsRouteRoute = AuthProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPicturesRouteRoute = AuthPicturesRouteRouteImport.update({
  id: '/pictures',
  path: '/pictures',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembersRouteRoute = AuthMembersRouteRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMachinesRouteRoute = AuthMachinesRouteRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsIndexRoute = AuthProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProductsRouteRoute,
} as any)
const AuthPicturesIndexRoute = AuthPicturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPicturesRouteRoute,
} as any)
const AuthMembersIndexRoute = AuthMembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMembersRouteRoute,
} as any)
const AuthMachinesIndexRoute = AuthMachinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMachinesRouteRoute,
} as any)
const InviteAcceptTokenRoute = InviteAcceptTokenRouteImport.update({
  id: '/invite/accept/$token',
  path: '/invite/accept/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdgeV1UsersRoute = ApiEdgeV1UsersRouteImport.update({
  id: '/api/edge/v1/users',
  path: '/api/edge/v1/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdgeV1PairRoute = ApiEdgeV1PairRouteImport.update({
  id: '/api/edge/v1/pair',
  path: '/api/edge/v1/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdgeV1HeartbeatRoute = ApiEdgeV1HeartbeatRouteImport.update({
  id: '/api/edge/v1/heartbeat',
  path: '/api/edge/v1/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMachinesMachineIdSmartfridgeRouteRoute =
  AuthMachinesMachineIdSmartfridgeRouteRouteImport.update({
    id: '/$machineId/smartfridge',
    path: '/$machineId/smartfridge',
    getParentRoute: () => AuthMachinesRouteRoute,
  } as any)
const AuthMachinesMachineIdCompartmentsRouteRoute =
  AuthMachinesMachineIdCompartmentsRouteRouteImport.update({
    id: '/$machineId/compartments',
    path: '/$machineId/compartments',
    getParentRoute: () => AuthMachinesRouteRoute,
  } as any)
const AuthMachinesMachineIdSmartfridgeIndexRoute =
  AuthMachinesMachineIdSmartfridgeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthMachinesMachineIdSmartfridgeRouteRoute,
  } as any)
const AuthMachinesMachineIdCompartmentsIndexRoute =
  AuthMachinesMachineIdCompartmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthMachinesMachineIdCompartmentsRouteRoute,
  } as any)
const ApiEdgeV1SyncPushRoute = ApiEdgeV1SyncPushRouteImport.update({
  id: '/api/edge/v1/sync/push',
  path: '/api/edge/v1/sync/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdgeV1SyncPullRoute = ApiEdgeV1SyncPullRouteImport.update({
  id: '/api/edge/v1/sync/pull',
  path: '/api/edge/v1/sync/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdgeV1AuthLoginRoute = ApiEdgeV1AuthLoginRouteImport.update({
  id: '/api/edge/v1/auth/login',
  path: '/api/edge/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/machines': typeof AuthMachinesRouteRouteWithChildren
  '/members': typeof AuthMembersRouteRouteWithChildren
  '/pictures': typeof AuthPicturesRouteRouteWithChildren
  '/products': typeof AuthProductsRouteRouteWithChildren
  '/login': typeof publicLoginRoute
  '/admin': typeof AuthAdminRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invite/accept/$token': typeof InviteAcceptTokenRoute
  '/machines/': typeof AuthMachinesIndexRoute
  '/members/': typeof AuthMembersIndexRoute
  '/pictures/': typeof AuthPicturesIndexRoute
  '/products/': typeof AuthProductsIndexRoute
  '/machines/$machineId/compartments': typeof AuthMachinesMachineIdCompartmentsRouteRouteWithChildren
  '/machines/$machineId/smartfridge': typeof AuthMachinesMachineIdSmartfridgeRouteRouteWithChildren
  '/api/edge/v1/heartbeat': typeof ApiEdgeV1HeartbeatRoute
  '/api/edge/v1/pair': typeof ApiEdgeV1PairRoute
  '/api/edge/v1/users': typeof ApiEdgeV1UsersRoute
  '/api/edge/v1/auth/login': typeof ApiEdgeV1AuthLoginRoute
  '/api/edge/v1/sync/pull': typeof ApiEdgeV1SyncPullRoute
  '/api/edge/v1/sync/push': typeof ApiEdgeV1SyncPushRoute
  '/machines/$machineId/compartments/': typeof AuthMachinesMachineIdCompartmentsIndexRoute
  '/machines/$machineId/smartfridge/': typeof AuthMachinesMachineIdSmartfridgeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/login': typeof publicLoginRoute
  '/admin': typeof AuthAdminRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invite/accept/$token': typeof InviteAcceptTokenRoute
  '/machines': typeof AuthMachinesIndexRoute
  '/members': typeof AuthMembersIndexRoute
  '/pictures': typeof AuthPicturesIndexRoute
  '/products': typeof AuthProductsIndexRoute
  '/api/edge/v1/heartbeat': typeof ApiEdgeV1HeartbeatRoute
  '/api/edge/v1/pair': typeof ApiEdgeV1PairRoute
  '/api/edge/v1/users': typeof ApiEdgeV1UsersRoute
  '/api/edge/v1/auth/login': typeof ApiEdgeV1AuthLoginRoute
  '/api/edge/v1/sync/pull': typeof ApiEdgeV1SyncPullRoute
  '/api/edge/v1/sync/push': typeof ApiEdgeV1SyncPushRoute
  '/machines/$machineId/compartments': typeof AuthMachinesMachineIdCompartmentsIndexRoute
  '/machines/$machineId/smartfridge': typeof AuthMachinesMachineIdSmartfridgeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/machines': typeof AuthMachinesRouteRouteWithChildren
  '/_auth/members': typeof AuthMembersRouteRouteWithChildren
  '/_auth/pictures': typeof AuthPicturesRouteRouteWithChildren
  '/_auth/products': typeof AuthProductsRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/(public)/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invite/accept/$token': typeof InviteAcceptTokenRoute
  '/_auth/machines/': typeof AuthMachinesIndexRoute
  '/_auth/members/': typeof AuthMembersIndexRoute
  '/_auth/pictures/': typeof AuthPicturesIndexRoute
  '/_auth/products/': typeof AuthProductsIndexRoute
  '/_auth/machines/$machineId/compartments': typeof AuthMachinesMachineIdCompartmentsRouteRouteWithChildren
  '/_auth/machines/$machineId/smartfridge': typeof AuthMachinesMachineIdSmartfridgeRouteRouteWithChildren
  '/api/edge/v1/heartbeat': typeof ApiEdgeV1HeartbeatRoute
  '/api/edge/v1/pair': typeof ApiEdgeV1PairRoute
  '/api/edge/v1/users': typeof ApiEdgeV1UsersRoute
  '/api/edge/v1/auth/login': typeof ApiEdgeV1AuthLoginRoute
  '/api/edge/v1/sync/pull': typeof ApiEdgeV1SyncPullRoute
  '/api/edge/v1/sync/push': typeof ApiEdgeV1SyncPushRoute
  '/_auth/machines/$machineId/compartments/': typeof AuthMachinesMachineIdCompartmentsIndexRoute
  '/_auth/machines/$machineId/smartfridge/': typeof AuthMachinesMachineIdSmartfridgeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/machines'
    | '/members'
    | '/pictures'
    | '/products'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/api/health'
    | '/api/auth/$'
    | '/invite/accept/$token'
    | '/machines/'
    | '/members/'
    | '/pictures/'
    | '/products/'
    | '/machines/$machineId/compartments'
    | '/machines/$machineId/smartfridge'
    | '/api/edge/v1/heartbeat'
    | '/api/edge/v1/pair'
    | '/api/edge/v1/users'
    | '/api/edge/v1/auth/login'
    | '/api/edge/v1/sync/pull'
    | '/api/edge/v1/sync/push'
    | '/machines/$machineId/compartments/'
    | '/machines/$machineId/smartfridge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/api/health'
    | '/api/auth/$'
    | '/invite/accept/$token'
    | '/machines'
    | '/members'
    | '/pictures'
    | '/products'
    | '/api/edge/v1/heartbeat'
    | '/api/edge/v1/pair'
    | '/api/edge/v1/users'
    | '/api/edge/v1/auth/login'
    | '/api/edge/v1/sync/pull'
    | '/api/edge/v1/sync/push'
    | '/machines/$machineId/compartments'
    | '/machines/$machineId/smartfridge'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/machines'
    | '/_auth/members'
    | '/_auth/pictures'
    | '/_auth/products'
    | '/(public)/login'
    | '/_auth/admin'
    | '/_auth/dashboard'
    | '/api/health'
    | '/(public)/'
    | '/api/auth/$'
    | '/invite/accept/$token'
    | '/_auth/machines/'
    | '/_auth/members/'
    | '/_auth/pictures/'
    | '/_auth/products/'
    | '/_auth/machines/$machineId/compartments'
    | '/_auth/machines/$machineId/smartfridge'
    | '/api/edge/v1/heartbeat'
    | '/api/edge/v1/pair'
    | '/api/edge/v1/users'
    | '/api/edge/v1/auth/login'
    | '/api/edge/v1/sync/pull'
    | '/api/edge/v1/sync/push'
    | '/_auth/machines/$machineId/compartments/'
    | '/_auth/machines/$machineId/smartfridge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  InviteAcceptTokenRoute: typeof InviteAcceptTokenRoute
  ApiEdgeV1HeartbeatRoute: typeof ApiEdgeV1HeartbeatRoute
  ApiEdgeV1PairRoute: typeof ApiEdgeV1PairRoute
  ApiEdgeV1UsersRoute: typeof ApiEdgeV1UsersRoute
  ApiEdgeV1AuthLoginRoute: typeof ApiEdgeV1AuthLoginRoute
  ApiEdgeV1SyncPullRoute: typeof ApiEdgeV1SyncPullRoute
  ApiEdgeV1SyncPushRoute: typeof ApiEdgeV1SyncPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/products': {
      id: '/_auth/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthProductsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pictures': {
      id: '/_auth/pictures'
      path: '/pictures'
      fullPath: '/pictures'
      preLoaderRoute: typeof AuthPicturesRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/members': {
      id: '/_auth/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthMembersRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/machines': {
      id: '/_auth/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AuthMachinesRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/': {
      id: '/_auth/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthProductsIndexRouteImport
      parentRoute: typeof AuthProductsRouteRoute
    }
    '/_auth/pictures/': {
      id: '/_auth/pictures/'
      path: '/'
      fullPath: '/pictures/'
      preLoaderRoute: typeof AuthPicturesIndexRouteImport
      parentRoute: typeof AuthPicturesRouteRoute
    }
    '/_auth/members/': {
      id: '/_auth/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthMembersIndexRouteImport
      parentRoute: typeof AuthMembersRouteRoute
    }
    '/_auth/machines/': {
      id: '/_auth/machines/'
      path: '/'
      fullPath: '/machines/'
      preLoaderRoute: typeof AuthMachinesIndexRouteImport
      parentRoute: typeof AuthMachinesRouteRoute
    }
    '/invite/accept/$token': {
      id: '/invite/accept/$token'
      path: '/invite/accept/$token'
      fullPath: '/invite/accept/$token'
      preLoaderRoute: typeof InviteAcceptTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edge/v1/users': {
      id: '/api/edge/v1/users'
      path: '/api/edge/v1/users'
      fullPath: '/api/edge/v1/users'
      preLoaderRoute: typeof ApiEdgeV1UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edge/v1/pair': {
      id: '/api/edge/v1/pair'
      path: '/api/edge/v1/pair'
      fullPath: '/api/edge/v1/pair'
      preLoaderRoute: typeof ApiEdgeV1PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edge/v1/heartbeat': {
      id: '/api/edge/v1/heartbeat'
      path: '/api/edge/v1/heartbeat'
      fullPath: '/api/edge/v1/heartbeat'
      preLoaderRoute: typeof ApiEdgeV1HeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/machines/$machineId/smartfridge': {
      id: '/_auth/machines/$machineId/smartfridge'
      path: '/$machineId/smartfridge'
      fullPath: '/machines/$machineId/smartfridge'
      preLoaderRoute: typeof AuthMachinesMachineIdSmartfridgeRouteRouteImport
      parentRoute: typeof AuthMachinesRouteRoute
    }
    '/_auth/machines/$machineId/compartments': {
      id: '/_auth/machines/$machineId/compartments'
      path: '/$machineId/compartments'
      fullPath: '/machines/$machineId/compartments'
      preLoaderRoute: typeof AuthMachinesMachineIdCompartmentsRouteRouteImport
      parentRoute: typeof AuthMachinesRouteRoute
    }
    '/_auth/machines/$machineId/smartfridge/': {
      id: '/_auth/machines/$machineId/smartfridge/'
      path: '/'
      fullPath: '/machines/$machineId/smartfridge/'
      preLoaderRoute: typeof AuthMachinesMachineIdSmartfridgeIndexRouteImport
      parentRoute: typeof AuthMachinesMachineIdSmartfridgeRouteRoute
    }
    '/_auth/machines/$machineId/compartments/': {
      id: '/_auth/machines/$machineId/compartments/'
      path: '/'
      fullPath: '/machines/$machineId/compartments/'
      preLoaderRoute: typeof AuthMachinesMachineIdCompartmentsIndexRouteImport
      parentRoute: typeof AuthMachinesMachineIdCompartmentsRouteRoute
    }
    '/api/edge/v1/sync/push': {
      id: '/api/edge/v1/sync/push'
      path: '/api/edge/v1/sync/push'
      fullPath: '/api/edge/v1/sync/push'
      preLoaderRoute: typeof ApiEdgeV1SyncPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edge/v1/sync/pull': {
      id: '/api/edge/v1/sync/pull'
      path: '/api/edge/v1/sync/pull'
      fullPath: '/api/edge/v1/sync/pull'
      preLoaderRoute: typeof ApiEdgeV1SyncPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edge/v1/auth/login': {
      id: '/api/edge/v1/auth/login'
      path: '/api/edge/v1/auth/login'
      fullPath: '/api/edge/v1/auth/login'
      preLoaderRoute: typeof ApiEdgeV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthMachinesMachineIdCompartmentsRouteRouteChildren {
  AuthMachinesMachineIdCompartmentsIndexRoute: typeof AuthMachinesMachineIdCompartmentsIndexRoute
}

const AuthMachinesMachineIdCompartmentsRouteRouteChildren: AuthMachinesMachineIdCompartmentsRouteRouteChildren =
  {
    AuthMachinesMachineIdCompartmentsIndexRoute:
      AuthMachinesMachineIdCompartmentsIndexRoute,
  }

const AuthMachinesMachineIdCompartmentsRouteRouteWithChildren =
  AuthMachinesMachineIdCompartmentsRouteRoute._addFileChildren(
    AuthMachinesMachineIdCompartmentsRouteRouteChildren,
  )

interface AuthMachinesMachineIdSmartfridgeRouteRouteChildren {
  AuthMachinesMachineIdSmartfridgeIndexRoute: typeof AuthMachinesMachineIdSmartfridgeIndexRoute
}

const AuthMachinesMachineIdSmartfridgeRouteRouteChildren: AuthMachinesMachineIdSmartfridgeRouteRouteChildren =
  {
    AuthMachinesMachineIdSmartfridgeIndexRoute:
      AuthMachinesMachineIdSmartfridgeIndexRoute,
  }

const AuthMachinesMachineIdSmartfridgeRouteRouteWithChildren =
  AuthMachinesMachineIdSmartfridgeRouteRoute._addFileChildren(
    AuthMachinesMachineIdSmartfridgeRouteRouteChildren,
  )

interface AuthMachinesRouteRouteChildren {
  AuthMachinesIndexRoute: typeof AuthMachinesIndexRoute
  AuthMachinesMachineIdCompartmentsRouteRoute: typeof AuthMachinesMachineIdCompartmentsRouteRouteWithChildren
  AuthMachinesMachineIdSmartfridgeRouteRoute: typeof AuthMachinesMachineIdSmartfridgeRouteRouteWithChildren
}

const AuthMachinesRouteRouteChildren: AuthMachinesRouteRouteChildren = {
  AuthMachinesIndexRoute: AuthMachinesIndexRoute,
  AuthMachinesMachineIdCompartmentsRouteRoute:
    AuthMachinesMachineIdCompartmentsRouteRouteWithChildren,
  AuthMachinesMachineIdSmartfridgeRouteRoute:
    AuthMachinesMachineIdSmartfridgeRouteRouteWithChildren,
}

const AuthMachinesRouteRouteWithChildren =
  AuthMachinesRouteRoute._addFileChildren(AuthMachinesRouteRouteChildren)

interface AuthMembersRouteRouteChildren {
  AuthMembersIndexRoute: typeof AuthMembersIndexRoute
}

const AuthMembersRouteRouteChildren: AuthMembersRouteRouteChildren = {
  AuthMembersIndexRoute: AuthMembersIndexRoute,
}

const AuthMembersRouteRouteWithChildren =
  AuthMembersRouteRoute._addFileChildren(AuthMembersRouteRouteChildren)

interface AuthPicturesRouteRouteChildren {
  AuthPicturesIndexRoute: typeof AuthPicturesIndexRoute
}

const AuthPicturesRouteRouteChildren: AuthPicturesRouteRouteChildren = {
  AuthPicturesIndexRoute: AuthPicturesIndexRoute,
}

const AuthPicturesRouteRouteWithChildren =
  AuthPicturesRouteRoute._addFileChildren(AuthPicturesRouteRouteChildren)

interface AuthProductsRouteRouteChildren {
  AuthProductsIndexRoute: typeof AuthProductsIndexRoute
}

const AuthProductsRouteRouteChildren: AuthProductsRouteRouteChildren = {
  AuthProductsIndexRoute: AuthProductsIndexRoute,
}

const AuthProductsRouteRouteWithChildren =
  AuthProductsRouteRoute._addFileChildren(AuthProductsRouteRouteChildren)

interface AuthRouteChildren {
  AuthMachinesRouteRoute: typeof AuthMachinesRouteRouteWithChildren
  AuthMembersRouteRoute: typeof AuthMembersRouteRouteWithChildren
  AuthPicturesRouteRoute: typeof AuthPicturesRouteRouteWithChildren
  AuthProductsRouteRoute: typeof AuthProductsRouteRouteWithChildren
  AuthAdminRoute: typeof AuthAdminRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMachinesRouteRoute: AuthMachinesRouteRouteWithChildren,
  AuthMembersRouteRoute: AuthMembersRouteRouteWithChildren,
  AuthPicturesRouteRoute: AuthPicturesRouteRouteWithChildren,
  AuthProductsRouteRoute: AuthProductsRouteRouteWithChildren,
  AuthAdminRoute: AuthAdminRoute,
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  publicIndexRoute: publicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  InviteAcceptTokenRoute: InviteAcceptTokenRoute,
  ApiEdgeV1HeartbeatRoute: ApiEdgeV1HeartbeatRoute,
  ApiEdgeV1PairRoute: ApiEdgeV1PairRoute,
  ApiEdgeV1UsersRoute: ApiEdgeV1UsersRoute,
  ApiEdgeV1AuthLoginRoute: ApiEdgeV1AuthLoginRoute,
  ApiEdgeV1SyncPullRoute: ApiEdgeV1SyncPullRoute,
  ApiEdgeV1SyncPushRoute: ApiEdgeV1SyncPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
