/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as AuthSymbolsRouteRouteImport } from './routes/_auth/symbols/route'
import { Route as AuthProductsRouteRouteImport } from './routes/_auth/products/route'
import { Route as AuthPicturesRouteRouteImport } from './routes/_auth/pictures/route'
import { Route as AuthMachinesRouteRouteImport } from './routes/_auth/machines/route'
import { Route as AuthEmployeesRouteRouteImport } from './routes/_auth/employees/route'
import { Route as AuthSymbolsIndexRouteImport } from './routes/_auth/symbols/index'
import { Route as AuthProductsIndexRouteImport } from './routes/_auth/products/index'
import { Route as AuthPicturesIndexRouteImport } from './routes/_auth/pictures/index'
import { Route as AuthMachinesIndexRouteImport } from './routes/_auth/machines/index'
import { Route as AuthEmployeesIndexRouteImport } from './routes/_auth/employees/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthMachinesMachineIdCompartmentsRouteRouteImport } from './routes/_auth/machines/$machineId/compartments/route'
import { Route as AuthMachinesMachineIdCompartmentsIndexRouteImport } from './routes/_auth/machines/$machineId/compartments/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSymbolsRouteRoute = AuthSymbolsRouteRouteImport.update({
  id: '/symbols',
  path: '/symbols',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsRouteRoute = AuthProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPicturesRouteRoute = AuthPicturesRouteRouteImport.update({
  id: '/pictures',
  path: '/pictures',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMachinesRouteRoute = AuthMachinesRouteRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmployeesRouteRoute = AuthEmployeesRouteRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSymbolsIndexRoute = AuthSymbolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSymbolsRouteRoute,
} as any)
const AuthProductsIndexRoute = AuthProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProductsRouteRoute,
} as any)
const AuthPicturesIndexRoute = AuthPicturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPicturesRouteRoute,
} as any)
const AuthMachinesIndexRoute = AuthMachinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMachinesRouteRoute,
} as any)
const AuthEmployeesIndexRoute = AuthEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthEmployeesRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMachinesMachineIdCompartmentsRouteRoute =
  AuthMachinesMachineIdCompartmentsRouteRouteImport.update({
    id: '/$machineId/compartments',
    path: '/$machineId/compartments',
    getParentRoute: () => AuthMachinesRouteRoute,
  } as any)
const AuthMachinesMachineIdCompartmentsIndexRoute =
  AuthMachinesMachineIdCompartmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthMachinesMachineIdCompartmentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/employees': typeof AuthEmployeesRouteRouteWithChildren
  '/machines': typeof AuthMachinesRouteRouteWithChildren
  '/pictures': typeof AuthPicturesRouteRouteWithChildren
  '/products': typeof AuthProductsRouteRouteWithChildren
  '/symbols': typeof AuthSymbolsRouteRouteWithChildren
  '/login': typeof publicLoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/employees/': typeof AuthEmployeesIndexRoute
  '/machines/': typeof AuthMachinesIndexRoute
  '/pictures/': typeof AuthPicturesIndexRoute
  '/products/': typeof AuthProductsIndexRoute
  '/symbols/': typeof AuthSymbolsIndexRoute
  '/machines/$machineId/compartments': typeof AuthMachinesMachineIdCompartmentsRouteRouteWithChildren
  '/machines/$machineId/compartments/': typeof AuthMachinesMachineIdCompartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/login': typeof publicLoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/employees': typeof AuthEmployeesIndexRoute
  '/machines': typeof AuthMachinesIndexRoute
  '/pictures': typeof AuthPicturesIndexRoute
  '/products': typeof AuthProductsIndexRoute
  '/symbols': typeof AuthSymbolsIndexRoute
  '/machines/$machineId/compartments': typeof AuthMachinesMachineIdCompartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/employees': typeof AuthEmployeesRouteRouteWithChildren
  '/_auth/machines': typeof AuthMachinesRouteRouteWithChildren
  '/_auth/pictures': typeof AuthPicturesRouteRouteWithChildren
  '/_auth/products': typeof AuthProductsRouteRouteWithChildren
  '/_auth/symbols': typeof AuthSymbolsRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/(public)/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/employees/': typeof AuthEmployeesIndexRoute
  '/_auth/machines/': typeof AuthMachinesIndexRoute
  '/_auth/pictures/': typeof AuthPicturesIndexRoute
  '/_auth/products/': typeof AuthProductsIndexRoute
  '/_auth/symbols/': typeof AuthSymbolsIndexRoute
  '/_auth/machines/$machineId/compartments': typeof AuthMachinesMachineIdCompartmentsRouteRouteWithChildren
  '/_auth/machines/$machineId/compartments/': typeof AuthMachinesMachineIdCompartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employees'
    | '/machines'
    | '/pictures'
    | '/products'
    | '/symbols'
    | '/login'
    | '/dashboard'
    | '/api/health'
    | '/api/auth/$'
    | '/employees/'
    | '/machines/'
    | '/pictures/'
    | '/products/'
    | '/symbols/'
    | '/machines/$machineId/compartments'
    | '/machines/$machineId/compartments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/health'
    | '/api/auth/$'
    | '/employees'
    | '/machines'
    | '/pictures'
    | '/products'
    | '/symbols'
    | '/machines/$machineId/compartments'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/employees'
    | '/_auth/machines'
    | '/_auth/pictures'
    | '/_auth/products'
    | '/_auth/symbols'
    | '/(public)/login'
    | '/_auth/dashboard'
    | '/api/health'
    | '/(public)/'
    | '/api/auth/$'
    | '/_auth/employees/'
    | '/_auth/machines/'
    | '/_auth/pictures/'
    | '/_auth/products/'
    | '/_auth/symbols/'
    | '/_auth/machines/$machineId/compartments'
    | '/_auth/machines/$machineId/compartments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/symbols': {
      id: '/_auth/symbols'
      path: '/symbols'
      fullPath: '/symbols'
      preLoaderRoute: typeof AuthSymbolsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products': {
      id: '/_auth/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthProductsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pictures': {
      id: '/_auth/pictures'
      path: '/pictures'
      fullPath: '/pictures'
      preLoaderRoute: typeof AuthPicturesRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/machines': {
      id: '/_auth/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AuthMachinesRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/employees': {
      id: '/_auth/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthEmployeesRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/symbols/': {
      id: '/_auth/symbols/'
      path: '/'
      fullPath: '/symbols/'
      preLoaderRoute: typeof AuthSymbolsIndexRouteImport
      parentRoute: typeof AuthSymbolsRouteRoute
    }
    '/_auth/products/': {
      id: '/_auth/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthProductsIndexRouteImport
      parentRoute: typeof AuthProductsRouteRoute
    }
    '/_auth/pictures/': {
      id: '/_auth/pictures/'
      path: '/'
      fullPath: '/pictures/'
      preLoaderRoute: typeof AuthPicturesIndexRouteImport
      parentRoute: typeof AuthPicturesRouteRoute
    }
    '/_auth/machines/': {
      id: '/_auth/machines/'
      path: '/'
      fullPath: '/machines/'
      preLoaderRoute: typeof AuthMachinesIndexRouteImport
      parentRoute: typeof AuthMachinesRouteRoute
    }
    '/_auth/employees/': {
      id: '/_auth/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthEmployeesIndexRouteImport
      parentRoute: typeof AuthEmployeesRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/machines/$machineId/compartments': {
      id: '/_auth/machines/$machineId/compartments'
      path: '/$machineId/compartments'
      fullPath: '/machines/$machineId/compartments'
      preLoaderRoute: typeof AuthMachinesMachineIdCompartmentsRouteRouteImport
      parentRoute: typeof AuthMachinesRouteRoute
    }
    '/_auth/machines/$machineId/compartments/': {
      id: '/_auth/machines/$machineId/compartments/'
      path: '/'
      fullPath: '/machines/$machineId/compartments/'
      preLoaderRoute: typeof AuthMachinesMachineIdCompartmentsIndexRouteImport
      parentRoute: typeof AuthMachinesMachineIdCompartmentsRouteRoute
    }
  }
}

interface AuthEmployeesRouteRouteChildren {
  AuthEmployeesIndexRoute: typeof AuthEmployeesIndexRoute
}

const AuthEmployeesRouteRouteChildren: AuthEmployeesRouteRouteChildren = {
  AuthEmployeesIndexRoute: AuthEmployeesIndexRoute,
}

const AuthEmployeesRouteRouteWithChildren =
  AuthEmployeesRouteRoute._addFileChildren(AuthEmployeesRouteRouteChildren)

interface AuthMachinesMachineIdCompartmentsRouteRouteChildren {
  AuthMachinesMachineIdCompartmentsIndexRoute: typeof AuthMachinesMachineIdCompartmentsIndexRoute
}

const AuthMachinesMachineIdCompartmentsRouteRouteChildren: AuthMachinesMachineIdCompartmentsRouteRouteChildren =
  {
    AuthMachinesMachineIdCompartmentsIndexRoute:
      AuthMachinesMachineIdCompartmentsIndexRoute,
  }

const AuthMachinesMachineIdCompartmentsRouteRouteWithChildren =
  AuthMachinesMachineIdCompartmentsRouteRoute._addFileChildren(
    AuthMachinesMachineIdCompartmentsRouteRouteChildren,
  )

interface AuthMachinesRouteRouteChildren {
  AuthMachinesIndexRoute: typeof AuthMachinesIndexRoute
  AuthMachinesMachineIdCompartmentsRouteRoute: typeof AuthMachinesMachineIdCompartmentsRouteRouteWithChildren
}

const AuthMachinesRouteRouteChildren: AuthMachinesRouteRouteChildren = {
  AuthMachinesIndexRoute: AuthMachinesIndexRoute,
  AuthMachinesMachineIdCompartmentsRouteRoute:
    AuthMachinesMachineIdCompartmentsRouteRouteWithChildren,
}

const AuthMachinesRouteRouteWithChildren =
  AuthMachinesRouteRoute._addFileChildren(AuthMachinesRouteRouteChildren)

interface AuthPicturesRouteRouteChildren {
  AuthPicturesIndexRoute: typeof AuthPicturesIndexRoute
}

const AuthPicturesRouteRouteChildren: AuthPicturesRouteRouteChildren = {
  AuthPicturesIndexRoute: AuthPicturesIndexRoute,
}

const AuthPicturesRouteRouteWithChildren =
  AuthPicturesRouteRoute._addFileChildren(AuthPicturesRouteRouteChildren)

interface AuthProductsRouteRouteChildren {
  AuthProductsIndexRoute: typeof AuthProductsIndexRoute
}

const AuthProductsRouteRouteChildren: AuthProductsRouteRouteChildren = {
  AuthProductsIndexRoute: AuthProductsIndexRoute,
}

const AuthProductsRouteRouteWithChildren =
  AuthProductsRouteRoute._addFileChildren(AuthProductsRouteRouteChildren)

interface AuthSymbolsRouteRouteChildren {
  AuthSymbolsIndexRoute: typeof AuthSymbolsIndexRoute
}

const AuthSymbolsRouteRouteChildren: AuthSymbolsRouteRouteChildren = {
  AuthSymbolsIndexRoute: AuthSymbolsIndexRoute,
}

const AuthSymbolsRouteRouteWithChildren =
  AuthSymbolsRouteRoute._addFileChildren(AuthSymbolsRouteRouteChildren)

interface AuthRouteChildren {
  AuthEmployeesRouteRoute: typeof AuthEmployeesRouteRouteWithChildren
  AuthMachinesRouteRoute: typeof AuthMachinesRouteRouteWithChildren
  AuthPicturesRouteRoute: typeof AuthPicturesRouteRouteWithChildren
  AuthProductsRouteRoute: typeof AuthProductsRouteRouteWithChildren
  AuthSymbolsRouteRoute: typeof AuthSymbolsRouteRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmployeesRouteRoute: AuthEmployeesRouteRouteWithChildren,
  AuthMachinesRouteRoute: AuthMachinesRouteRouteWithChildren,
  AuthPicturesRouteRoute: AuthPicturesRouteRouteWithChildren,
  AuthProductsRouteRoute: AuthProductsRouteRouteWithChildren,
  AuthSymbolsRouteRoute: AuthSymbolsRouteRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  publicIndexRoute: publicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
