/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as AuthProductsRouteRouteImport } from './routes/_auth/products/route'
import { Route as AuthMachinesRouteRouteImport } from './routes/_auth/machines/route'
import { Route as AuthProductsIndexRouteImport } from './routes/_auth/products/index'
import { Route as AuthMachinesIndexRouteImport } from './routes/_auth/machines/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthMachinesMachineIdCompartmentsRouteRouteImport } from './routes/_auth/machines_/$machineId/compartments/route'
import { Route as AuthMachinesMachineIdCompartmentsIndexRouteImport } from './routes/_auth/machines_/$machineId/compartments/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProductsRouteRoute = AuthProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMachinesRouteRoute = AuthMachinesRouteRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsIndexRoute = AuthProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProductsRouteRoute,
} as any)
const AuthMachinesIndexRoute = AuthMachinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMachinesRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMachinesMachineIdCompartmentsRouteRoute =
  AuthMachinesMachineIdCompartmentsRouteRouteImport.update({
    id: '/machines_/$machineId/compartments',
    path: '/machines/$machineId/compartments',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthMachinesMachineIdCompartmentsIndexRoute =
  AuthMachinesMachineIdCompartmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthMachinesMachineIdCompartmentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/machines': typeof AuthMachinesRouteRouteWithChildren
  '/products': typeof AuthProductsRouteRouteWithChildren
  '/login': typeof publicLoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/machines/': typeof AuthMachinesIndexRoute
  '/products/': typeof AuthProductsIndexRoute
  '/machines/$machineId/compartments': typeof AuthMachinesMachineIdCompartmentsRouteRouteWithChildren
  '/machines/$machineId/compartments/': typeof AuthMachinesMachineIdCompartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/login': typeof publicLoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/machines': typeof AuthMachinesIndexRoute
  '/products': typeof AuthProductsIndexRoute
  '/machines/$machineId/compartments': typeof AuthMachinesMachineIdCompartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/machines': typeof AuthMachinesRouteRouteWithChildren
  '/_auth/products': typeof AuthProductsRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/(public)/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/machines/': typeof AuthMachinesIndexRoute
  '/_auth/products/': typeof AuthProductsIndexRoute
  '/_auth/machines_/$machineId/compartments': typeof AuthMachinesMachineIdCompartmentsRouteRouteWithChildren
  '/_auth/machines_/$machineId/compartments/': typeof AuthMachinesMachineIdCompartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/machines'
    | '/products'
    | '/login'
    | '/dashboard'
    | '/api/auth/$'
    | '/machines/'
    | '/products/'
    | '/machines/$machineId/compartments'
    | '/machines/$machineId/compartments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/auth/$'
    | '/machines'
    | '/products'
    | '/machines/$machineId/compartments'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/machines'
    | '/_auth/products'
    | '/(public)/login'
    | '/_auth/dashboard'
    | '/(public)/'
    | '/api/auth/$'
    | '/_auth/machines/'
    | '/_auth/products/'
    | '/_auth/machines_/$machineId/compartments'
    | '/_auth/machines_/$machineId/compartments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/products': {
      id: '/_auth/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthProductsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/machines': {
      id: '/_auth/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AuthMachinesRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/': {
      id: '/_auth/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthProductsIndexRouteImport
      parentRoute: typeof AuthProductsRouteRoute
    }
    '/_auth/machines/': {
      id: '/_auth/machines/'
      path: '/'
      fullPath: '/machines/'
      preLoaderRoute: typeof AuthMachinesIndexRouteImport
      parentRoute: typeof AuthMachinesRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/machines_/$machineId/compartments': {
      id: '/_auth/machines_/$machineId/compartments'
      path: '/machines/$machineId/compartments'
      fullPath: '/machines/$machineId/compartments'
      preLoaderRoute: typeof AuthMachinesMachineIdCompartmentsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/machines_/$machineId/compartments/': {
      id: '/_auth/machines_/$machineId/compartments/'
      path: '/'
      fullPath: '/machines/$machineId/compartments/'
      preLoaderRoute: typeof AuthMachinesMachineIdCompartmentsIndexRouteImport
      parentRoute: typeof AuthMachinesMachineIdCompartmentsRouteRoute
    }
  }
}

interface AuthMachinesRouteRouteChildren {
  AuthMachinesIndexRoute: typeof AuthMachinesIndexRoute
}

const AuthMachinesRouteRouteChildren: AuthMachinesRouteRouteChildren = {
  AuthMachinesIndexRoute: AuthMachinesIndexRoute,
}

const AuthMachinesRouteRouteWithChildren =
  AuthMachinesRouteRoute._addFileChildren(AuthMachinesRouteRouteChildren)

interface AuthProductsRouteRouteChildren {
  AuthProductsIndexRoute: typeof AuthProductsIndexRoute
}

const AuthProductsRouteRouteChildren: AuthProductsRouteRouteChildren = {
  AuthProductsIndexRoute: AuthProductsIndexRoute,
}

const AuthProductsRouteRouteWithChildren =
  AuthProductsRouteRoute._addFileChildren(AuthProductsRouteRouteChildren)

interface AuthMachinesMachineIdCompartmentsRouteRouteChildren {
  AuthMachinesMachineIdCompartmentsIndexRoute: typeof AuthMachinesMachineIdCompartmentsIndexRoute
}

const AuthMachinesMachineIdCompartmentsRouteRouteChildren: AuthMachinesMachineIdCompartmentsRouteRouteChildren =
  {
    AuthMachinesMachineIdCompartmentsIndexRoute:
      AuthMachinesMachineIdCompartmentsIndexRoute,
  }

const AuthMachinesMachineIdCompartmentsRouteRouteWithChildren =
  AuthMachinesMachineIdCompartmentsRouteRoute._addFileChildren(
    AuthMachinesMachineIdCompartmentsRouteRouteChildren,
  )

interface AuthRouteChildren {
  AuthMachinesRouteRoute: typeof AuthMachinesRouteRouteWithChildren
  AuthProductsRouteRoute: typeof AuthProductsRouteRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthMachinesMachineIdCompartmentsRouteRoute: typeof AuthMachinesMachineIdCompartmentsRouteRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMachinesRouteRoute: AuthMachinesRouteRouteWithChildren,
  AuthProductsRouteRoute: AuthProductsRouteRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthMachinesMachineIdCompartmentsRouteRoute:
    AuthMachinesMachineIdCompartmentsRouteRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicIndexRoute: publicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
